[package]
name = "gameserver"
version = "0.0.0"
edition = "2021"

[dependencies]
libhydrogen = "0.4"
prost = "0.11"
tokio = { version = "~1.20", features = ["rt-multi-thread", "io-util", "net", "macros", "sync"] }

[build-dependencies]
prost-build = "0.11"
